# Generated by Django 6.0 on 2025-12-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptexecution',
            name='variables',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
