# Generated by Django 6.0 on 2025-12-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_scriptexecution_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='default_variables',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
