# Generated by Django 6.0 on 2025-12-10 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_script_default_variables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='admin_files/', verbose_name='Fichier')),
                ('file_type', models.CharField(choices=[('model', 'Modèle de données'), ('env', 'Fichier environnement'), ('config', 'Configuration'), ('template', 'Template'), ('other', 'Autre')], max_length=20, verbose_name='Type')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Taille (octets)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Importé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fichier Admin',
                'verbose_name_plural': 'Fichiers Admin',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
