# Generated by Django 5.1.3 on 2026-09-09 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_alter_adminfile_id_alter_script_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('success', 'Terminé'), ('error', 'Erreur')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=300)),
                ('input_file', models.FileField(blank=True, null=True, upload_to='workflow/inputs/', verbose_name='Fichier stock (input.xlsx)')),
                ('backoffice_file', models.FileField(blank=True, null=True, upload_to='workflow/backoffice/', verbose_name='Données backoffice (.csv)')),
                ('training_file', models.FileField(blank=True, null=True, upload_to='workflow/training/', verbose_name="Dataset d'entraînement (.csv)")),
                ('output_file', models.FileField(blank=True, null=True, upload_to='workflow/outputs/', verbose_name='Fichier Excel résultat')),
                ('logs', models.TextField(blank=True)),
                ('nb_lignes_input', models.IntegerField(default=0)),
                ('nb_lignes_output', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow Produits',
                'verbose_name_plural': 'Workflows Produits',
                'ordering': ['-created_at'],
            },
        ),
    ]
