# Generated by Django 5.1.3 on 2026-09-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_add_product_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='productworkflow',
            name='output_dupliques_file',
            field=models.FileField(blank=True, null=True, upload_to='workflow/outputs/', verbose_name='Fichier Excel produits dupliqués'),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='output_erreurs_file',
            field=models.FileField(blank=True, null=True, upload_to='workflow/outputs/', verbose_name='Fichier Excel lignes avec erreurs'),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='output_non_dupliques_file',
            field=models.FileField(blank=True, null=True, upload_to='workflow/outputs/', verbose_name='Fichier Excel produits non dupliqués'),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='workflow/outputs/', verbose_name='Fichier Excel résultat (produits finaux)'),
        ),
    ]
