# Generated by Django 5.1.3 on 2026-09-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0007_add_workflow_output_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='output_dupliques_file',
            field=models.FileField(blank=True, null=True, upload_to='workflow/resultats/', verbose_name='Fichier Excel produits dupliqués'),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='output_erreurs_file',
            field=models.FileField(blank=True, null=True, upload_to='workflow/resultats/', verbose_name='Fichier Excel lignes avec erreurs'),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='workflow/resultats/', verbose_name='Fichier Excel résultat (produits finaux)'),
        ),
        migrations.AlterField(
            model_name='productworkflow',
            name='output_non_dupliques_file',
            field=models.FileField(blank=True, null=True, upload_to='workflow/resultats/', verbose_name='Fichier Excel produits non dupliqués'),
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scriptexecution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
